### ISSUE TITLE
PHP 8.2 Support

### ISSUE THREAD

**Issue by dakujem** [laminas/laminas-xml#12]
### Feature Request

I'm testing an RC release of PHP 8.2, but this package fails to install due to version restrictions in `composer.json`.
I would welcome the addition of PHP 8.2 to to the list of supported PHP versions.

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

Hello, I understand that this package is security-only and feature-complete. However - does that mean no support for future PHP versions is coming?

What about adding a benevolent version constaraint? That would allow us to install the package, and, if issues do occur, the community could provide MRs. That would reduce the amount of work needed for the maintainers ofthis package to minimum.

**Comment by Ocramius** [comment]
See https://github.com/laminas/.github/pull/40

**Comment by dakujem** [comment]
Sorry, I fail to understand. It's a documentation update.

MY original post boils down to these two questions:
- Will there be an update for this repo that supports PHP 8.2?
- Is there anything I can help with?

**Comment by Ocramius** [comment]
> Will there be an update for this repo that supports PHP 8.2?

Yes

 > Is there anything I can help with?

Include a `renovate.json` referencing the work done @ https://github.com/laminas/.github/pull/40, and in theory, we should get PHP 8.2 added to the dependency range via automation.

**Comment by Ocramius** [comment]
@internalsystemerror I tried looking at the latest renovate runs:

https://app.renovatebot.com/dashboard#github/laminas/laminas-xml/872647167

```
DEBUG: packageFiles with updates
{
  "baseBranch": "1.5.x",
  "config": {
    "composer": [
      {
        "packageFile": "composer.json",
        "deps": [
          {
            "depType": "require",
            "depName": "php",
            "currentValue": "^7.3 || ~8.0.0 || ~8.1.0",
            "datasource": "github-tags",
            "packageName": "php/php-src",
            "extractVersion": "^php-(?<version>.*)$",
            "depIndex": 0,
            "updates": [],
            "warnings": [],
            "versioning": "composer",
            "sourceUrl": "https://github.com/php/php-src",
            "currentVersion": "8.1.12"
          },
```

I suppose it will pick up `8.2.0` once it becomes `currentVersion`?

**Comment by internalsystemerror** [comment]
The `currentVersion` there is what renovate thinks the current version used based on the `currentValue` is I believe. It should propose `8.2.0` once that gets released, but it seems that the unstable versions aren't being picked up as I would have expected `8.2.0RC5`.

**Comment by Ocramius** [comment]
Yeah, should've been that, according to https://github.com/laminas/.github/pull/37 :thinking:

**Comment by Ocramius** [comment]
Handled in #16
