### ISSUE TITLE
PHP 8.0 support

### ISSUE THREAD

**Issue by boesing** [laminas/laminas-xml#2]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

#### Summary

To be prepared for the december release of PHP 8.0, this repository has some additional TODOs to be tested against the new major version.

In order to make this repository compatible, one has to follow these steps:

- [ ] Modify `composer.json` to provide support for PHP 8.0 by adding the constraint `~8.0.0`
- [ ] Modify `composer.json` to drop support for PHP less than 7.3
- [ ] Modify `composer.json` to implement phpunit 9.3 which supports PHP 7.3+
- [ ] Modify `.travis.yml` to ignore platform requirements when installing composer dependencies (simply add `--ignore-platform-reqs` to `COMPOSER_ARGS` env variable)
- [ ] Modify `.travis.yml` to add PHP 8.0 to the matrix (*NOTE*: Do not allow failures as PHP 8.0 has a feature freeze since 2020-08-04!)
- [ ] Modify source code in case there are incompatibilities with PHP 8.0

**Comment by xvilo** [comment]
@boesing I'm not sure if it's the right way or if it is already wanted, but created a small PR fixing at least 1 PHP 8.0 issue :) https://github.com/laminas/laminas-xml/pull/3/files

As an extra note I did not find any immediate issues with phpunit:

```
$ php -v
PHP 8.0.0RC3 (cli) (built: Oct 31 2020 17:06:24) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.0-dev, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.0RC3, Copyright (c), by Zend Technologies

$ php composer.phar --version
Composer version 2.0.7 2020-11-13 17:31:06

$ php composer.phar test
> phpunit --colors=always
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

.................R.......                                         25 / 25 (100%)

Time: 175 ms, Memory: 4.00 MB

There was 1 risky test:

1) LaminasTest\Xml\SecurityTest::testScanForXXE
This test did not perform any assertions

/projects/laminas-xml/test/SecurityTest.php:36

OK, but incomplete, skipped, or risky tests!
Tests: 25, Assertions: 45, Risky: 1.
```
