### ISSUE TITLE
PHP 8.1 Support

### ISSUE THREAD

**Issue by dakujem** [laminas/laminas-xml#7]
Hello. I stumbled upon being unable to run app with this package in PHP 8.1 environment.

This is what I get from Composer.
```
- laminas/laminas-xml[1.3.0, ..., 1.4.x-dev] require php ^7.3 || ~8.0.0 -> your php version (8.1.0) does not satisfy that requirement.
```

The issue is that the constraint in `composer.json` is as follows:
```json
    "require": {
        "php": "^7.3 || ~8.0.0",
        "laminas/laminas-zendframework-bridge": "^1.0"
    },
```
([seen here](https://github.com/laminas/laminas-xml/blob/1.4.x/composer.json#L24))

I suggest changing `"php": "^7.3 || ~8.0.0",` to `"php": "^7.3 || ^8.0",` to support future versions of PHP.

**Comment by tobias-trozowski** [comment]
@dakujem see comment from froschdesign at https://github.com/laminas/laminas-xmlrpc/issues/18#issuecomment-981113218

**Comment by dakujem** [comment]
Thank you for your response. As I understand it, the support for PHP 8.1 is under development then.

FYI, I'm using the `laminas/laminas-xml2json` package that requires this one.

**Comment by froschdesign** [comment]
@dakujem 
> As I understand it, the support for PHP 8.1 is under development then.

Any help is welcome! 👍

**Comment by dakujem** [comment]
Sure, but the PR is already out :-) https://github.com/laminas/laminas-xml/pull/8

**Comment by tobias-trozowski** [comment]
@froschdesign not directly related to php 8.1 but as you ask me to do the same thing yesterday... does it makes sense to also remove the dependency on zendframework-bridge?

**Comment by froschdesign** [comment]
@tobias-trozowski 
As a separate pull request would be good, then we will have an extra entry in the release notes.
Thanks in advance! 👍
